### ISSUE TITLE
Recorder app is not opening and forced closed 

### ISSUE THREAD

**Issue by sohail1234** [AospExtended/thread_template#41]
Using rom on note5pro Android 10  and the [Log link ](https://del.dog/melamaivil)

**Comment by iKeramat** [comment]
Hmmm Android 11 !?

**Comment by sohail1234** [comment]
@iKeramat 
![Screenshot_20200229-180813_Settings](https://user-images.githubusercontent.com/11853488/75607575-8b27a880-5b1e-11ea-9bc7-7aa97d524bd8.png)
